-- Emoji search chooser!
-- Adapted from https://github.com/aldur/dotfiles/blob/master/osx/hammerspoon/init.lua
--
-- emojis.json is generated by update-emojis.py in this directory; re-run it to
-- pick up new Unicode releases. Its rows are already in the shape hs.chooser
-- wants, so loading is a decode and a handoff with no per-row work.

-- Focus the last active window
local wf = hs.window.filter
local function focusLastFocused()
  local lastFocused = wf.defaultCurrentSpace:getWindows(wf.sortByFocusedLast)
  if #lastFocused > 0 then lastFocused[1]:focus() end
end


local chooser = hs.chooser.new(function(choice)
  if not choice then focusLastFocused() return end
  hs.pasteboard.setContents(choice.chars)
  focusLastFocused()
  hs.eventtap.keyStrokes(hs.pasteboard.getContents())
end)


local isLoaded = false
local function loadChoices()
  if isLoaded then return end
  isLoaded = true

  local file = assert(io.open(hs.configdir .. '/emojis.json'))
  local json = file:read('*a')
  file:close()

  chooser:rows(10)
  chooser:searchSubText(true)
  chooser:choices(hs.json.decode(json))
end

-- Loading ~2k choices takes long enough to notice, so get it out of the way in
-- the background rather than on the first keystroke. Deferred so it doesn't
-- hold up the rest of the config.
hs.timer.doAfter(2, loadChoices)

local Commands = {}
Commands.choose = function()
  loadChoices() -- no-op unless the hotkey beat the background load
  chooser:show()
end

return Commands
