#!/usr/bin/env node

/**
 * Clean up a sea of old screenshots and screen recordings on the Desktop
 */

const { execSync } = require('child_process')
const { existsSync, readdirSync, mkdirSync } = require('fs')
const { homedir } = require('os')
const path = require('path')

const desktop = path.join(homedir(), 'Desktop')
const tidyUpDir = path.join(desktop, 'old_screenshots')
const tidyUpDirExists = existsSync(tidyUpDir)

// Fail silently if there are no matching files to move
const trySync = (cmd) => {
  try {
    execSync(cmd)
  } catch (err) {
    if (!err.message.includes('No such file or directory')) throw err;
  }
}

const run = () => {
  if (!tidyUpDirExists) mkdirSync(tidyUpDir)

  trySync(`mv ${desktop}/Screenshot* ${tidyUpDir}`)
  trySync(`mv ${desktop}/Screen\\ Recording* ${tidyUpDir}`)
}

run()
