#!/usr/bin/env bun

import { execSync } from 'child_process'
import { parseArgs } from 'util'

declare const Bun: { argv: string[] }

type Chunk = {
  fileName: string,
  lines: { lineText: string, lineNumber: number }[]
}

// Get the default branch for this repo (eg 'main'). By default, look for changes relative to that ref
const baseBranch = execSync('basename $(git symbolic-ref --short refs/remotes/origin/HEAD)', { encoding: 'utf8' }).trim()

const diffFileBoundaryRegex = /^diff --git a\//m
const fileNameRegex = /\n\+\+\+ b\/(\S+)\n/
const chunkBoundaryRegex = /\n@@ [^\+]+\+/m
const lineNumberRegex = /^\d+/

const parseCLI = () => {
  const { values, positionals } = parseArgs({
    argv: Bun.argv,
    options: {
      terms: { type: 'string', default: 'TODO|FIXME|console.log|debugger|@ts-ignore|: ?any' },
      output: { type: 'string', default: 'pretty' }, // 'pretty' or 'vimgrep'
      base: { type: 'string', default: baseBranch },
    },
    strict: true,
    allowPositionals: true,
  })
  return { flags: values }
}

// Quick and dirty terminal colorize utils.
// See https://stackoverflow.com/questions/9781218/how-to-change-node-jss-console-font-color
const _makeColorizer = (colorCode: string) => (str: string) => `\x1b[${colorCode}m${str}\x1b[0m`
const colorize = {
  blue: _makeColorizer('34'),
  cyan: _makeColorizer('36'),
  yellow: _makeColorizer('33'),
}

const getRawDiff = (flags: Record<string, string>) => {
  const diffCmd = `git diff -U0 -G '${flags.terms}' ${flags.base}`
  return execSync(diffCmd, { encoding: 'utf8' })
}

const parseChunks = (diffOutput: string, termsRegex: RegExp): Chunk[] => {
  return diffOutput
    .split(diffFileBoundaryRegex)
    .flatMap(rawChunk => {
      const fileNameMatch = rawChunk.match(fileNameRegex)
      if (!fileNameMatch) return []

      return rawChunk.split(chunkBoundaryRegex)
        .flatMap(innerChunk => {
          const lineNumberMatch = innerChunk.match(lineNumberRegex)
          if (!lineNumberMatch) return []
          const chunkStartLine = parseInt(lineNumberMatch[0])

          const matchingAddedLines = innerChunk
            .split('\n')
            .slice(1)                         // Remove rest of @@ context line
            .filter(l => l.startsWith('+'))   // Filter for added lines only
            .map((lineText, idx) => ({ lineText: lineText.slice(1), lineNumber: idx + chunkStartLine }))
            .filter(({ lineText }) => termsRegex.test(lineText))   // Filter for lines with our grep terms
          if (!matchingAddedLines.length) return []

          return [{
            fileName: fileNameMatch[1],
            lines: matchingAddedLines
          }]
        })
    })
}

const makeHighlighter = (termsRegex: RegExp) => (line: string) => line.replace(termsRegex, colorize.yellow)

const formatters = {
  pretty: (chunks: Chunk[], highlighter: ReturnType<typeof makeHighlighter>) => {
    const fileSections = chunks.map(chunk => {
      const { fileName, lines } = chunk
      const location = `${colorize.cyan(fileName)}`
      const fmtLine = ({ lineText, lineNumber }) => highlighter(
        `${colorize.blue(`${lineNumber}:`)} ${lineText.trim()}`
      )

      return `${location}\n${lines.map(fmtLine).join('\n')}`
    })
    return fileSections.join('\n\n')
  },

  vimgrep: (chunks: Chunk[]) => {
    return chunks.flatMap(chunk => chunk.lines.map(({ lineText, lineNumber }) => (
      // Note: character position is hardwired to "1" below for now
      `${chunk.fileName}:${lineNumber}:${lineText.trim()}`
    ))).join('\n')
  }
}

const main = (argv: string[]) => {
  const { flags } = parseCLI()
  const termsRegex = new RegExp(flags.terms, 'g')

  const rawOutput = getRawDiff(flags)
  const chunks = parseChunks(rawOutput, termsRegex)
  const highlighter = makeHighlighter(termsRegex)

  const output = flags.output === 'vimgrep' ?
    formatters.vimgrep(chunks) :
    formatters.pretty(chunks, highlighter)
  console.log(output)
}

main(Bun.argv)

// vim: set filetype=typescript:
